volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/megardes/data/wordpress
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/megardes/data/mariadb

networks:
  inception_network:
    name: inception_network


services:
  nginx:
    build:
      context: ./requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception_network

  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - ../secrets/.env

  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception_network
    env_file:
      - ../secrets/.env
    depends_on:
      - mariadb

